<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Flamenco.Packaging.Dpkg/Flamenco.Packaging.Dpkg.csproj" />
    <ProjectReference Include="../Flamenco.Shared/Flamenco.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
  </ItemGroup>

</Project>
