name: flamenco
base: core24
summary: Package maintenance tool for Ubuntu Toolchains
description: |
  Flamenco is a CLI tool that helps toolchain developers manage many
  different package versions and releases from a single debian
  folder source tree.
adopt-info: flamenco
license: GPL-3.0
source-code: https://github.com/canonical/flamenco
issues: https://github.com/canonical/flamenco/issues
contact: dotnet@lists.canonical.com
icon: images/icon-512.webp

grade: devel
confinement: strict
platforms:
  amd64:
    build-on:
      - amd64
    build-for:
      - amd64
  arm64:
    build-on:
      - arm64
    build-for:
      - arm64

assumes:
  - snap-env
  - common-data-dir

parts:
  flamenco:
    source: .
    plugin: dotnet
    dotnet-project: src/Flamenco.Console/Flamenco.Console.csproj
    dotnet-version: "8.0"
    dotnet-properties:
      DefineConstants: SNAPCRAFT
    build-packages:
      - git
      - distro-info-data
    override-build: |
      FLAMENCO_VERSION="$(cat src/Flamenco.Console/Flamenco.Console.csproj | grep \<Version\> | awk -F'[<>]' '{print $3}')"
      GIT_HASH="$(git rev-parse --short HEAD)"
      craftctl set version="${FLAMENCO_VERSION}+git.${GIT_HASH}"
      craftctl default
    organize:
      "*":
        usr/lib/flamenco/
    override-prime: |
      craftctl default
      mv "$CRAFT_PRIME"/usr/lib/flamenco/Flamenco.Console "$CRAFT_PRIME"/usr/lib/flamenco/flamenco

  dpkg-buildpackage-dependencies:
    plugin: nil
    build-packages:
      - base-files
    stage-packages:
      - dpkg
      - dpkg-dev
      - fakeroot
      - gcc
      - tar
      - xz-utils
    override-build: |
      # needed by dpkg-genbuildinfo:
      cp --recursive /etc/dpkg "$CRAFT_PART_INSTALL"/etc
      cp /var/lib/dpkg/status "$CRAFT_PART_INSTALL"/var/lib/dpkg/

  git-external-source-dependencies:
    plugin: nil
    stage-packages:
      - git
      - make

layout:
  /etc/dpkg:
    bind: $SNAP_COMMON/dpkg
  /etc/perl:
    bind: $SNAP/etc/perl
  /usr/bin/fakeroot:
    symlink: $SNAP/usr/bin/fakeroot-sysv
  /usr/bin/perl:
    symlink: $SNAP/usr/bin/perl
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl-base:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl-base
  /usr/share/dpkg:
    bind: $SNAP/usr/share/dpkg
  /usr/share/perl:
    bind: $SNAP/usr/share/perl
  /usr/share/perl5:
    bind: $SNAP/usr/share/perl5
  /var/lib/dpkg:
    bind: $SNAP/var/lib/dpkg

apps:
  flamenco:
    environment:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "1"
      X_DEBIAN_MULTIARCH_TRIPLET: $CRAFT_ARCH_TRIPLET_BUILD_FOR
    command: usr/lib/flamenco/flamenco
    extensions: [ dotnet8 ]
    plugs:
      - network
      - home
      - removable-media

lint:
  ignore:
    - library:
      - lib*
